version: "3"
services:
  basebackend:
    build: .
    ports: 
      - "3000:3000"
    volumes:
      - ./:/app 
      - /app/node_modules
    environment:
      - PORT=3000
    
    # for starting a service first then your base backend later.
    depends_on:
      - serviceName

      # env_file:
      #   -./.env
